Repository microsoft/maro, pull requests merged in 2020-11, with the labels that each got.

#174 package version updated with several bug fix, refinement, new example
  docs/source/examples/cim.rst
  docs/source/examples/citi_bike.rst
  docs/source/installation/k8s_cluster_provisioning_on_azure.rst
  docs/source/scenarios/citi_bike.rst
  examples/cim/dqn/components/experience_shaper.py
  examples/cim/dqn/config.yml
  examples/cim/dqn/dist_actor.py
  examples/cim/dqn/dist_learner.py
  examples/cim/dqn/multi_process_launcher.py
  examples/cim/dqn/single_process_launcher.py
  examples/cim/gnn/action_shaper.py
  examples/cim/gnn/actor.py
  examples/cim/gnn/actor_critic.py
  examples/cim/gnn/agent.py
  examples/cim/gnn/agent_manager.py
  examples/cim/gnn/config.yml
  examples/cim/gnn/experience_shaper.py
  examples/cim/gnn/launcher.py
  examples/cim/gnn/learner.py
  examples/cim/gnn/numpy_store.py
  examples/cim/gnn/shared_structure.py
  examples/cim/gnn/simple_gnn.py
  examples/cim/gnn/state_shaper.py
  examples/cim/gnn/utils.py
  examples/proxy/broadcast.py
  examples/proxy/scatter.py
  examples/proxy/send.py
  maro/__misc__.py
  maro/cli/grass/executors/grass_azure_executor.py
  maro/cli/k8s/executors/k8s_azure_executor.py
  maro/cli/k8s/job.py
  maro/cli/k8s/lib/k8s_configs/job.yml
  maro/cli/maro.py
  maro/rl/agent/abs_agent.py
  maro/rl/dist_topologies/single_learner_multi_actor_sync_mode.py
  maro/rl/learner/simple_learner.py
  maro/rl/storage/column_based_store.py
  maro/utils/logger.py
  tests/cli/grass/test_data/README.md
  tests/cli/grass/test_grass.py
  tests/cli/k8s/test_data/README.md
  tests/cli/k8s/test_k8s.py
  tests/cli/templates/test_grass_azure_start_job_dqn.yml
  tests/cli/templates/test_k8s_azure_start_job_dqn.yml
Labels: awaiting review, v0.1

#185 Fix build wheel issue on linux
  .github/workflows/build_wheel.yml
Labels: awaiting review

#187 V0.2 finance update for comments
  examples/hello_world/finance/000002.bin
  examples/hello_world/finance/000004.bin
  examples/hello_world/finance/000005.bin
  examples/hello_world/finance/000006.bin
  examples/hello_world/finance/demo.py
  maro/simulator/scenarios/finance/account.py
  maro/simulator/scenarios/finance/business_engine.py
  maro/simulator/scenarios/finance/common/common.py
  maro/simulator/scenarios/finance/topologies/demo/config.yml
Labels: finance

#178 V0.2 Logical operator overloading for EarlyStoppingChecker
  examples/cim/dqn/config.yml
  examples/cim/dqn/dist_actor.py
  examples/cim/dqn/dist_learner.py
  examples/cim/dqn/single_process_launcher.py
  maro/rl/__init__.py
  maro/rl/early_stopping/abs_early_stopping_checker.py
  maro/rl/early_stopping/simple_early_stopping_checker.py
Labels: awaiting review, last step, v0.2, 💡 feature request

#176 V0.2 skip connection
  examples/cim/dqn/components/agent_manager.py
  examples/cim/dqn/components/experience_shaper.py
  examples/cim/dqn/config.yml
  maro/rl/__init__.py
  maro/rl/models/fc_block.py
  maro/rl/models/fc_net.py
  maro/rl/models/learning_model.py
Labels: awaiting review, last step, v0.2, 💡 feature request

#183 V0.2 feature predefined image
  examples/cim/dqn/components/config.py
  examples/cim/dqn/dist_actor.py
  examples/cim/dqn/dist_learner.py
  examples/cim/dqn/distributed_config.yml
  maro/cli/grass/executors/grass_azure_executor.py
  maro/cli/grass/executors/grass_executor.py
  maro/cli/grass/lib/agents/maro-master-agent.service
  maro/cli/grass/lib/agents/maro-node-agent.service
  maro/cli/grass/lib/azure/create_build_node_image_vm/parameters.json
  maro/cli/grass/lib/azure/create_build_node_image_vm/template.json
  maro/cli/grass/lib/azure/create_master/parameters.json
  maro/cli/grass/lib/azure/create_master/template.json
  maro/cli/grass/lib/azure/create_node/parameters.json
  maro/cli/grass/lib/azure/create_node/template.json
  maro/cli/grass/lib/azure/create_vnet/parameters.json
  maro/cli/grass/lib/azure/create_vnet/template.json
  maro/cli/grass/lib/scripts/init_build_node_image_vm.py
  maro/cli/grass/lib/scripts/init_master.py
  maro/cli/grass/lib/scripts/init_node.py
  maro/cli/grass/utils/copy.py
  maro/cli/k8s/executors/k8s_azure_executor.py
  maro/cli/utils/executors/azure_executor.py
  maro/rl/early_stopping/__init__.py
  maro/utils/logger.py
  tests/cli/grass/test_grass.py
  tests/cli/k8s/test_k8s.py
  tests/cli/templates/test_grass_azure_create.yml
  tests/cli/templates/test_grass_azure_start_job_dqn.yml
  tests/cli/templates/test_k8s_azure_create.yml
  tests/cli/templates/test_k8s_azure_start_job_dqn.yml
  tests/cli/utils.py
Labels: last step

#158 V0.2 feature proxy rejoin
  examples/proxy/broadcast.py
  examples/proxy/scatter.py
  examples/proxy/send.py
  maro/cli/grass/executors/grass_azure_executor.py
  maro/cli/grass/executors/grass_executor.py
  maro/cli/grass/lib/agents/exception.py
  maro/cli/grass/lib/agents/master_agent.py
  maro/cli/grass/lib/agents/node_agent.py
  maro/cli/grass/lib/agents/resource.py
  maro/cli/grass/lib/agents/utils.py
  maro/cli/grass/lib/scripts/create_killed_job_ticket.py
  maro/cli/grass/lib/scripts/create_pending_job_ticket.py
  maro/cli/grass/lib/scripts/delete_pending_job_ticket.py
  maro/cli/grass/lib/scripts/get_containers_details.py
  maro/cli/grass/lib/scripts/load_master_agent_service.py
  maro/cli/grass/lib/scripts/utils.py
  maro/cli/utils/executors/azure_executor.py
  maro/communication/dist_decorator.py
  maro/communication/driver/abs_driver.py
  maro/communication/driver/zmq_driver.py
  maro/communication/message.py
  maro/communication/proxy.py
  maro/communication/registry_table.py
  maro/communication/utils/default_parameters.py
  maro/rl/dist_topologies/single_learner_multi_actor_sync_mode.py
  maro/utils/__init__.py
  maro/utils/checkpoint.py
  maro/utils/exception/communication_exception.py
  maro/utils/exception/error_code.py
  maro/utils/exit_code.py
  setup.py
  tests/checkpoint/config.yml
  tests/checkpoint/test_checkpoint.py
  tests/checkpoint/test_checkpoint_parameters.json
  tests/checkpoint/test_checkpoint_template.json
  tests/communication/__init__.py
  tests/communication/test_decorator.py
  tests/communication/test_proxy.py
  tests/communication/test_registry_table.py
  tests/communication/test_rejoin.py
  tests/communication/test_zmq_driver.py
  tests/requirements.test.txt
Labels: awaiting review, v0.2, 💡 feature request
