Repository microsoft/maro, pull requests merged in 2020-10, with the labels that each got.

#144 switch the key and value of handler_dict in decorator
  maro/communication/dist_decorator.py
  tests/communication/test_decorator.py
  tests/communication/test_proxy.py
  tests/communication/test_registry_table.py
  tests/communication/test_zmq_driver.py
  tests/communication/utils.py
Labels: v0.1

#147 V0.1 annotation
  maro/simulator/abs_core.py
  maro/simulator/core.py
  maro/simulator/scenarios/abs_business_engine.py
  maro/simulator/scenarios/cim/business_engine.py
  maro/simulator/scenarios/citi_bike/business_engine.py
  maro/simulator/scenarios/citi_bike/station_reward.py
  maro/simulator/scenarios/citi_bike/topologies/ny.201801/config.yml
  maro/simulator/scenarios/citi_bike/topologies/ny.201802/config.yml
  maro/simulator/scenarios/citi_bike/topologies/ny.201803/config.yml
  maro/simulator/scenarios/citi_bike/topologies/ny.201804/config.yml
  maro/simulator/scenarios/citi_bike/topologies/ny.201805/config.yml
  maro/simulator/scenarios/citi_bike/topologies/ny.201806/config.yml
  maro/simulator/scenarios/citi_bike/topologies/ny.201807/config.yml
  maro/simulator/scenarios/citi_bike/topologies/ny.201808/config.yml
  maro/simulator/scenarios/citi_bike/topologies/ny.201809/config.yml
  maro/simulator/scenarios/citi_bike/topologies/ny.201810/config.yml
  maro/simulator/scenarios/citi_bike/topologies/ny.201811/config.yml
  maro/simulator/scenarios/citi_bike/topologies/ny.201812/config.yml
  maro/simulator/scenarios/citi_bike/topologies/ny.201901/config.yml
  maro/simulator/scenarios/citi_bike/topologies/ny.201902/config.yml
  maro/simulator/scenarios/citi_bike/topologies/ny.201903/config.yml
  maro/simulator/scenarios/citi_bike/topologies/ny.201904/config.yml
  maro/simulator/scenarios/citi_bike/topologies/ny.201905/config.yml
  maro/simulator/scenarios/citi_bike/topologies/ny.201906/config.yml
  maro/simulator/scenarios/citi_bike/topologies/ny.201907/config.yml
  maro/simulator/scenarios/citi_bike/topologies/ny.201908/config.yml
  maro/simulator/scenarios/citi_bike/topologies/ny.201909/config.yml
  maro/simulator/scenarios/citi_bike/topologies/ny.201910/config.yml
  maro/simulator/scenarios/citi_bike/topologies/ny.201911/config.yml
  maro/simulator/scenarios/citi_bike/topologies/ny.201912/config.yml
  maro/simulator/scenarios/citi_bike/topologies/ny.202001/config.yml
  maro/simulator/scenarios/citi_bike/topologies/ny.202002/config.yml
  maro/simulator/scenarios/citi_bike/topologies/ny.202003/config.yml
  maro/simulator/scenarios/citi_bike/topologies/ny.202004/config.yml
  maro/simulator/scenarios/citi_bike/topologies/ny.202005/config.yml
  maro/simulator/scenarios/citi_bike/topologies/ny.202006/config.yml
  maro/simulator/scenarios/citi_bike/topologies/toy.3s_4t/config.yml
  maro/simulator/scenarios/citi_bike/topologies/toy.4s_4t/config.yml
  maro/simulator/scenarios/citi_bike/topologies/toy.5s_6t/config.yml
  maro/simulator/scenarios/citi_bike/topologies/train/config.yml
  tests/dummy/dummy_business_engine.py
Labels: v0.1

#156 Event payload details for env.summary
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  examples/cim/dqn/README.md
  examples/cim/dqn/components/state_shaper.py
  maro/data_lib/__init__.py
  maro/data_lib/cim/entities.py
  maro/simulator/core.py
  maro/simulator/scenarios/abs_business_engine.py
  maro/simulator/scenarios/cim/business_engine.py
  maro/simulator/scenarios/cim/common.py
  maro/simulator/scenarios/citi_bike/business_engine.py
  maro/simulator/scenarios/citi_bike/common.py
  maro/simulator/scenarios/citi_bike/meta/trips.yml
Labels: v0.2

#157 V0.1 issues in CLI
  docs/source/installation/k8s_cluster_provisioning_on_azure.rst
  examples/cim/dqn/dist_actor.py
  examples/cim/dqn/dist_learner.py
  maro/cli/grass/executors/grass_azure_executor.py
  maro/cli/k8s/executors/k8s_azure_executor.py
  maro/cli/k8s/job.py
  maro/cli/k8s/lib/k8s_configs/job.yml
  maro/cli/maro.py
  maro/utils/logger.py
  tests/cli/grass/test_data/README.md
  tests/cli/grass/test_grass.py
  tests/cli/k8s/test_data/README.md
  tests/cli/k8s/test_k8s.py
  tests/cli/templates/test_grass_azure_start_job_dqn.yml
  tests/cli/templates/test_k8s_azure_start_job_dqn.yml
Labels: v0.1

#60 initalize gnn network for CIM problem
  examples/cim/dqn/components/experience_shaper.py
  examples/cim/dqn/single_process_launcher.py
  examples/cim/gnn/action_shaper.py
  examples/cim/gnn/actor.py
  examples/cim/gnn/actor_critic.py
  examples/cim/gnn/agent.py
  examples/cim/gnn/agent_manager.py
  examples/cim/gnn/config.yml
  examples/cim/gnn/experience_shaper.py
  examples/cim/gnn/launcher.py
  examples/cim/gnn/learner.py
  examples/cim/gnn/numpy_store.py
  examples/cim/gnn/shared_structure.py
  examples/cim/gnn/simple_gnn.py
  examples/cim/gnn/state_shaper.py
  examples/cim/gnn/utils.py
Labels: v0.1

#166 V0.1 store unpicklable bug fix
  maro/rl/agent/abs_agent.py
  maro/rl/storage/column_based_store.py
Labels: v0.1, 🐛 bug

#167 V0.1 confusing component naming fix
  examples/cim/dqn/config.yml
  examples/cim/dqn/multi_process_launcher.py
  maro/rl/dist_topologies/single_learner_multi_actor_sync_mode.py
  maro/rl/learner/simple_learner.py
Labels: v0.1, 🐛 bug

#159 V0.2 online lp for citi bike
  examples/citi_bike/greedy/README.md
  examples/citi_bike/greedy/config.yml
  examples/citi_bike/online_lp/DemandDiff.ny201910.2040.png
  examples/citi_bike/online_lp/DemandDiff.ny201910.2400.png
  examples/citi_bike/online_lp/LogDemand.ny201910.2400.png
  examples/citi_bike/online_lp/README.md
  examples/citi_bike/online_lp/citi_bike_ilp.py
  examples/citi_bike/online_lp/config.yml
  examples/citi_bike/online_lp/launcher.py
  maro/forecasting/__init__.py
  maro/forecasting/moving_average.py
  maro/simulator/scenarios/citi_bike/business_engine.py
  maro/utils/__init__.py
  requirements.dev.txt
Labels: awaiting review, citi bike, v0.2

#165 V0.2 rl toolkit refinement
  docs/source/examples/multi_agent_dqn_cim.rst
  docs/source/key_components/rl_toolkit.rst
  examples/cim/dqn/README.md
  examples/cim/dqn/components/agent.py
  examples/cim/dqn/components/agent_manager.py
  examples/cim/dqn/components/config.py
  examples/cim/dqn/config.yml
  examples/cim/dqn/dist_actor.py
  examples/cim/dqn/dist_learner.py
  examples/cim/dqn/multi_process_launcher.py
  examples/cim/dqn/single_process_launcher.py
  maro/rl/__init__.py
  maro/rl/actor/simple_actor.py
  maro/rl/agent/abs_agent.py
  maro/rl/agent/abs_agent_manager.py
  maro/rl/agent/simple_agent_manager.py
  maro/rl/algorithms/abs_algorithm.py
  maro/rl/algorithms/dqn.py
  maro/rl/algorithms/torch/__init__.py
  maro/rl/algorithms/torch/abs_algorithm.py
  maro/rl/algorithms/torch/dqn.py
  maro/rl/dist_topologies/experience_collection.py
  maro/rl/dist_topologies/single_learner_multi_actor_sync_mode.py
  maro/rl/early_stopping/abs_early_stopping_checker.py
  maro/rl/early_stopping/simple_early_stopping_checker.py
  maro/rl/explorer/abs_explorer.py
  maro/rl/explorer/simple_explorer.py
  maro/rl/learner/abs_learner.py
  maro/rl/learner/simple_learner.py
  maro/rl/models/fc_net.py
  maro/rl/models/learning_model.py
  maro/rl/models/torch/__init__.py
  maro/rl/models/torch/decision_layers.py
  maro/rl/models/torch/mlp_representation.py
  maro/rl/shaping/experience_shaper.py
  maro/rl/storage/column_based_store.py
  maro/rl/storage/utils.py
  maro/utils/exception/error_code.py
  maro/utils/exception/rl_toolkit_exception.py
  notebooks/container_inventory_management/rl_formulation.ipynb
Labels: awaiting review, v0.2, 💡 feature request
