Repository microsoft/maro, pull requests merged in 2021-02, with the labels that each got.

#272 Fix noteboook typos
  notebooks/bike_repositioning/interact_with_environment.ipynb
  notebooks/container_inventory_management/interact_with_environment.ipynb
  notebooks/vm_scheduling/interact_with_environment.ipynb
Labels: cim, citi bike, vm scheduling, 📚 doc

#219 Refine joint decision sequential action mode
  maro/simulator/abs_core.py
  maro/simulator/core.py
Labels: awaiting review

#266 Add vector env support
  examples/vector_env/hello.py
  maro/simulator/scenarios/cim/business_engine.py
  maro/simulator/scenarios/cim/common.py
  maro/simulator/scenarios/citi_bike/common.py
  maro/vector_env/__init__.py
  maro/vector_env/env_process.py
  maro/vector_env/vector_env.py
  tests/test_env.py
  tests/test_snapshot.py
  tests/test_vector_env.py
Labels: awaiting review

#255 v0.2_rule_based_algorithm
  examples/vm_scheduling/rule_based_algorithm/agent.py
  examples/vm_scheduling/rule_based_algorithm/best_fit.py
  examples/vm_scheduling/rule_based_algorithm/bin_packing.py
  examples/vm_scheduling/rule_based_algorithm/config.yml
  examples/vm_scheduling/rule_based_algorithm/first_fit.py
  examples/vm_scheduling/rule_based_algorithm/launcher.py
  examples/vm_scheduling/rule_based_algorithm/random_pick.py
  examples/vm_scheduling/rule_based_algorithm/round_robin.py
  examples/vm_scheduling/rule_based_algorithm/rule_based_algorithm.py
Labels: vm scheduling

#281 Bug fix: Exclude tests folder from package.
  scripts/build_sdist.bat
  scripts/build_sdist.sh
  setup.py
Labels: awaiting review

#273 Add slot filter functions for node attribute
  .gitignore
  maro/backends/_raw_backend_.pyx
  maro/backends/backend.pxd
  maro/backends/backend.pyx
  maro/backends/frame.pyx
  maro/backends/np_backend.pyx
  maro/backends/raw/frame.cpp
  maro/backends/raw/frame.h
  maro/backends/raw_backend.pxd
  maro/backends/raw_backend.pyx
  tests/test_frame.py
Labels: awaiting review

#285 Master vm doc - data preparation
  docs/source/scenarios/vm_scheduling.rst
Labels: awaiting review, vm scheduling, 📚 doc

#279 Feature: Add a cli command to support create new project.
  MANIFEST.in
  docs/source/index.rst
  docs/source/scenarios/command_line.rst
  maro/cli/maro.py
  maro/cli/project_generator/__init__.py
  maro/cli/project_generator/project_generator.py
  maro/cli/project_generator/templates/business_engine.py.jinja
  maro/cli/project_generator/templates/common.py.jinja
  maro/cli/project_generator/templates/events.py.jinja
  maro/cli/project_generator/templates/frame_builder.py.jinja
  maro/cli/project_generator/templates/runner.base.py.jinja
  maro/cli/project_generator/templates/runner.customize.py.jinja
  requirements.dev.txt
  setup.py
Labels: awaiting review
